name: Build filtered feed

env:
  OWNER: ${{ github.repository_owner }}

on:
  push:
    branches: [ main ]
    paths:
      - build.js
      - package.json
      - .github/workflows/build.yml
      - '**/*.md'
  workflow_dispatch: {}
  schedule:
    - cron: "0 * * * *" # hourly, UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Show workspace files
        run: |
          pwd
          ls -la
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          [ -f package-lock.json ] && echo "Found package-lock.json" || echo "NO package-lock.json"

      - name: Setup Node with cache (if lockfile present)
        if: ${{ hashFiles('package-lock.json', 'npm-shrinkwrap.json', 'yarn.lock') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            package-lock.json
            npm-shrinkwrap.json
            yarn.lock

      - name: Setup Node (no cache)
        if: ${{ hashFiles('package-lock.json', 'npm-shrinkwrap.json', 'yarn.lock') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci --no-audit --no-fund || npm i --no-audit --no-fund

      - name: Build feed
        run: npm run build
        env:
          SOURCE: https://www.nutrient.io/blog/feed.xml
          KEYWORDS: iOS,Objective-C,Swift,SwiftUI
          FEED_TITLE: Nutrient Blog — iOS & Swift (filtered)
          SELF_URL: https://${{ env.OWNER }}.github.io/nutrient-ios-swift.xml
          MAX_ITEMS: "120"
          CONCURRENCY: "6"
          TIMEOUT_MS: "15000"
          RETRIES: "2"

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
          keep_files: true
          force_orphan: true
